# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'feedback.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FeedbackUI(object):
    def setupUi(self, FeedbackUI):
        FeedbackUI.setObjectName("FeedbackUI")
        FeedbackUI.resize(703, 617)
        self.verticalLayoutWidget = QtWidgets.QWidget(FeedbackUI)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 681, 554))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.name.setObjectName("name")
        self.horizontalLayout.addWidget(self.name)
        self.task = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.task.setObjectName("task")
        self.horizontalLayout.addWidget(self.task)
        self.date = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.date.setObjectName("date")
        self.horizontalLayout.addWidget(self.date)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.md = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.md.setStatusTip("")
        self.md.setAccessibleName("")
        self.md.setInputMethodHints(QtCore.Qt.ImhNone)
        self.md.setMaximum(20)
        self.md.setPageStep(5)
        self.md.setSliderPosition(10)
        self.md.setOrientation(QtCore.Qt.Horizontal)
        self.md.setObjectName("md")
        self.verticalLayout.addWidget(self.md)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.pd = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.pd.setStatusTip("")
        self.pd.setAccessibleName("")
        self.pd.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pd.setMaximum(20)
        self.pd.setPageStep(5)
        self.pd.setSliderPosition(10)
        self.pd.setOrientation(QtCore.Qt.Horizontal)
        self.pd.setObjectName("pd")
        self.verticalLayout.addWidget(self.pd)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_8.addWidget(self.label_17, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.td = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.td.setStatusTip("")
        self.td.setAccessibleName("")
        self.td.setInputMethodHints(QtCore.Qt.ImhNone)
        self.td.setMaximum(20)
        self.td.setPageStep(5)
        self.td.setSliderPosition(10)
        self.td.setOrientation(QtCore.Qt.Horizontal)
        self.td.setObjectName("td")
        self.verticalLayout.addWidget(self.td)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_9.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_9.addWidget(self.label_19, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_11.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_23.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_11.addWidget(self.label_23, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.p = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.p.setStatusTip("")
        self.p.setAccessibleName("")
        self.p.setInputMethodHints(QtCore.Qt.ImhNone)
        self.p.setMaximum(20)
        self.p.setPageStep(5)
        self.p.setSliderPosition(10)
        self.p.setOrientation(QtCore.Qt.Horizontal)
        self.p.setObjectName("p")
        self.verticalLayout.addWidget(self.p)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_12.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_12.addWidget(self.label_25, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_28 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_14.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_29.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_14.addWidget(self.label_29, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.e = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.e.setStatusTip("")
        self.e.setAccessibleName("")
        self.e.setInputMethodHints(QtCore.Qt.ImhNone)
        self.e.setMaximum(20)
        self.e.setPageStep(5)
        self.e.setSliderPosition(10)
        self.e.setOrientation(QtCore.Qt.Horizontal)
        self.e.setObjectName("e")
        self.verticalLayout.addWidget(self.e)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_32 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_16.addWidget(self.label_32)
        self.label_33 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_33.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_16.addWidget(self.label_33, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_30 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_15.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_31.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_15.addWidget(self.label_31, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.f = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.f.setStatusTip("")
        self.f.setAccessibleName("")
        self.f.setInputMethodHints(QtCore.Qt.ImhNone)
        self.f.setMaximum(20)
        self.f.setPageStep(5)
        self.f.setSliderPosition(10)
        self.f.setOrientation(QtCore.Qt.Horizontal)
        self.f.setObjectName("f")
        self.verticalLayout.addWidget(self.f)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_34 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_17.addWidget(self.label_34)
        self.label_35 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_35.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_17.addWidget(self.label_35, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.pushButton = QtWidgets.QPushButton(FeedbackUI)
        self.pushButton.setGeometry(QtCore.QRect(500, 580, 181, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(FeedbackUI)
        QtCore.QMetaObject.connectSlotsByName(FeedbackUI)

    def retranslateUi(self, FeedbackUI):
        _translate = QtCore.QCoreApplication.translate
        FeedbackUI.setWindowTitle(_translate("FeedbackUI", "Form"))
        self.label.setText(_translate("FeedbackUI", "NASA Task Load Index Survey"))
        self.label_5.setText(_translate("FeedbackUI", "Name"))
        self.label_4.setText(_translate("FeedbackUI", "Task"))
        self.label_3.setText(_translate("FeedbackUI", "Date"))
        self.label_8.setText(_translate("FeedbackUI", "Mental Demand"))
        self.label_6.setText(_translate("FeedbackUI", " How mentally demanding was the task?"))
        self.label_9.setText(_translate("FeedbackUI", "Very Low"))
        self.label_10.setText(_translate("FeedbackUI", "Very High"))
        self.label_11.setText(_translate("FeedbackUI", "Physical Demand"))
        self.label_7.setText(_translate("FeedbackUI", "How physically demanding was the task?"))
        self.label_12.setText(_translate("FeedbackUI", "Very Low"))
        self.label_13.setText(_translate("FeedbackUI", "Very High"))
        self.label_16.setText(_translate("FeedbackUI", "Temporal Demand"))
        self.label_17.setText(_translate("FeedbackUI", "How hurried or rushed was the pace of the task?"))
        self.label_18.setText(_translate("FeedbackUI", "Very Low"))
        self.label_19.setText(_translate("FeedbackUI", "Very High"))
        self.label_22.setText(_translate("FeedbackUI", " Performance"))
        self.label_23.setText(_translate("FeedbackUI", "How successful were you in accomplishing whatyou were asked to do?"))
        self.label_24.setText(_translate("FeedbackUI", "Very Low"))
        self.label_25.setText(_translate("FeedbackUI", "Very High"))
        self.label_28.setText(_translate("FeedbackUI", "Effort"))
        self.label_29.setText(_translate("FeedbackUI", "How hard did you have to work to  accomplishyour level of performance?"))
        self.label_32.setText(_translate("FeedbackUI", "Very Low"))
        self.label_33.setText(_translate("FeedbackUI", "Very High"))
        self.label_30.setText(_translate("FeedbackUI", "Frustration"))
        self.label_31.setText(_translate("FeedbackUI", "How insecure, discouraged, irritated, stressed,and annoyed wereyou?"))
        self.label_34.setText(_translate("FeedbackUI", "Very Low"))
        self.label_35.setText(_translate("FeedbackUI", "Very High"))
        self.pushButton.setText(_translate("FeedbackUI", "Submit"))

