# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_lite.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1044, 624)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 1021, 601))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_144 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_144.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_144.setObjectName("label_144")
        self.verticalLayout_13.addWidget(self.label_144)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_4)
        self.comboBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_13.addWidget(self.comboBox)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_13.addWidget(self.pushButton)
        self.label_71 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_71.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_71.setObjectName("label_71")
        self.verticalLayout_13.addWidget(self.label_71)
        self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_13.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_13.addWidget(self.radioButton_2)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.radioButton_3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_16.addWidget(self.radioButton_3)
        self.checkBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_4)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_16.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_4)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_16.addWidget(self.checkBox_2)
        self.verticalLayout_13.addLayout(self.horizontalLayout_16)
        self.setRPButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.setRPButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.setRPButton.setObjectName("setRPButton")
        self.verticalLayout_13.addWidget(self.setRPButton)
        self.label_72 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_72.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_72.setFont(font)
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName("label_72")
        self.verticalLayout_13.addWidget(self.label_72)
        self.connectRPButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectRPButton.sizePolicy().hasHeightForWidth())
        self.connectRPButton.setSizePolicy(sizePolicy)
        self.connectRPButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.connectRPButton.setAutoFillBackground(False)
        self.connectRPButton.setCheckable(False)
        self.connectRPButton.setObjectName("connectRPButton")
        self.verticalLayout_13.addWidget(self.connectRPButton)
        self.open_cam = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_cam.sizePolicy().hasHeightForWidth())
        self.open_cam.setSizePolicy(sizePolicy)
        self.open_cam.setMaximumSize(QtCore.QSize(200, 16777215))
        self.open_cam.setAutoFillBackground(False)
        self.open_cam.setCheckable(False)
        self.open_cam.setObjectName("open_cam")
        self.verticalLayout_13.addWidget(self.open_cam)
        self.horizontalLayout_6.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_30 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_30.setObjectName("label_30")
        self.verticalLayout.addWidget(self.label_30)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_31 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_3.addWidget(self.label_31)
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_3.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_3.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_3.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_3.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_3.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_3.addWidget(self.label_21)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_32 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_2.addWidget(self.label_32)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_34 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_8.addWidget(self.label_34)
        self.label_35 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_8.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_8.addWidget(self.label_36)
        self.label_37 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_8.addWidget(self.label_37)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_14.addLayout(self.horizontalLayout)
        self.horizontalLayout_6.addLayout(self.verticalLayout_14)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_6)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_144.setText(_translate("Dialog", "Robot Selection"))
        self.pushButton.setText(_translate("Dialog", "Confirm"))
        self.label_71.setText(_translate("Dialog", "Control Mode"))
        self.radioButton.setText(_translate("Dialog", "Only left arm"))
        self.radioButton_2.setText(_translate("Dialog", "Only right arm"))
        self.radioButton_3.setText(_translate("Dialog", "Both arms"))
        self.checkBox.setText(_translate("Dialog", "Mirror"))
        self.checkBox_2.setText(_translate("Dialog", "Reverse"))
        self.setRPButton.setText(_translate("Dialog", "Confirm"))
        self.label_72.setText(_translate("Dialog", "TextLabel"))
        self.connectRPButton.setText(_translate("Dialog", "Enable/Disable Connection"))
        self.open_cam.setText(_translate("Dialog", "Open Camera View"))
        self.label_30.setText(_translate("Dialog", "Joint Name"))
        self.label_2.setText(_translate("Dialog", "Joint0"))
        self.label.setText(_translate("Dialog", "Joint1"))
        self.label_4.setText(_translate("Dialog", "Joint2"))
        self.label_3.setText(_translate("Dialog", "Joint3"))
        self.label_5.setText(_translate("Dialog", "Joint4"))
        self.label_7.setText(_translate("Dialog", "Joint5"))
        self.label_6.setText(_translate("Dialog", "Joint6"))
        self.label_31.setText(_translate("Dialog", "Angle(radian)"))
        self.label_15.setText(_translate("Dialog", "j0a"))
        self.label_16.setText(_translate("Dialog", "j1a"))
        self.label_17.setText(_translate("Dialog", "j2a"))
        self.label_18.setText(_translate("Dialog", "j3a"))
        self.label_19.setText(_translate("Dialog", "j4a"))
        self.label_20.setText(_translate("Dialog", "j5a"))
        self.label_21.setText(_translate("Dialog", "j6a"))
        self.label_32.setText(_translate("Dialog", "Velocity(rad/s)"))
        self.label_8.setText(_translate("Dialog", "j0v"))
        self.label_9.setText(_translate("Dialog", "j1v"))
        self.label_10.setText(_translate("Dialog", "j2v"))
        self.label_11.setText(_translate("Dialog", "j3v"))
        self.label_12.setText(_translate("Dialog", "j4v"))
        self.label_13.setText(_translate("Dialog", "j5v"))
        self.label_14.setText(_translate("Dialog", "j6v"))
        self.label_34.setText(_translate("Dialog", "Cartesian Pose"))
        self.label_35.setText(_translate("Dialog", "Xpose"))
        self.label_36.setText(_translate("Dialog", "Ypose"))
        self.label_37.setText(_translate("Dialog", "Zpose"))

