# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(613, 370)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(140, 20, 311, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.un_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.un_input.setObjectName("un_input")
        self.verticalLayout.addWidget(self.un_input)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setEnabled(True)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.pw_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.pw_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pw_input.setObjectName("pw_input")
        self.verticalLayout.addWidget(self.pw_input)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(150, 220, 291, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.su_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.su_btn.setObjectName("su_btn")
        self.horizontalLayout.addWidget(self.su_btn)
        self.li_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.li_btn.setObjectName("li_btn")
        self.horizontalLayout.addWidget(self.li_btn)
        self.login_state = QtWidgets.QLabel(self.centralwidget)
        self.login_state.setGeometry(QtCore.QRect(110, 270, 371, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_state.sizePolicy().hasHeightForWidth())
        self.login_state.setSizePolicy(sizePolicy)
        self.login_state.setText("")
        self.login_state.setObjectName("login_state")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 613, 22))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionTrina2 = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pics/Hiro_Logo_WPITheme-300x108.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTrina2.setIcon(icon)
        self.actionTrina2.setObjectName("actionTrina2")
        self.actionRobopuppet = QtWidgets.QAction(MainWindow)
        self.actionRobopuppet.setObjectName("actionRobopuppet")
        self.actionFeedback = QtWidgets.QAction(MainWindow)
        self.actionFeedback.setObjectName("actionFeedback")
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionTrina2)
        self.menuAbout.addAction(self.actionRobopuppet)
        self.menuAbout.addAction(self.actionFeedback)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Username"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.su_btn.setText(_translate("MainWindow", "Sign Up"))
        self.li_btn.setText(_translate("MainWindow", "Log In"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionTrina2.setText(_translate("MainWindow", "Trina2"))
        self.actionRobopuppet.setText(_translate("MainWindow", "Robopuppet"))
        self.actionFeedback.setText(_translate("MainWindow", "Feedback"))

