# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(351, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 311, 212))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.un_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.un_input.setObjectName("un_input")
        self.verticalLayout.addWidget(self.un_input)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setEnabled(True)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.pw_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.pw_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pw_input.setObjectName("pw_input")
        self.verticalLayout.addWidget(self.pw_input)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.usertype_box = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.usertype_box.setObjectName("usertype_box")
        self.usertype_box.addItem("")
        self.usertype_box.addItem("")
        self.verticalLayout.addWidget(self.usertype_box)
        self.login_state = QtWidgets.QLabel(self.centralwidget)
        self.login_state.setGeometry(QtCore.QRect(110, 270, 371, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_state.sizePolicy().hasHeightForWidth())
        self.login_state.setSizePolicy(sizePolicy)
        self.login_state.setText("")
        self.login_state.setObjectName("login_state")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 230, 311, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.warning_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.warning_label.setText("")
        self.warning_label.setObjectName("warning_label")
        self.verticalLayout_2.addWidget(self.warning_label)
        self.su_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.su_btn.setObjectName("su_btn")
        self.verticalLayout_2.addWidget(self.su_btn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 351, 22))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionTrina2 = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pics/Hiro_Logo_WPITheme-300x108.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTrina2.setIcon(icon)
        self.actionTrina2.setObjectName("actionTrina2")
        self.actionRobopuppet = QtWidgets.QAction(MainWindow)
        self.actionRobopuppet.setObjectName("actionRobopuppet")
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionTrina2)
        self.menuAbout.addAction(self.actionRobopuppet)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Username"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.label_3.setText(_translate("MainWindow", "Default Trina2 Robot #"))
        self.label_4.setText(_translate("MainWindow", "User type"))
        self.usertype_box.setItemText(0, _translate("MainWindow", "Regular"))
        self.usertype_box.setItemText(1, _translate("MainWindow", "Admin"))
        self.su_btn.setText(_translate("MainWindow", "Sign Up"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionTrina2.setText(_translate("MainWindow", "Trina2"))
        self.actionRobopuppet.setText(_translate("MainWindow", "Robopuppet"))

