# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(913, 552)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 891, 531))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 891, 501))
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget_2.setTabsClosable(False)
        self.tabWidget_2.setMovable(False)
        self.tabWidget_2.setTabBarAutoHide(True)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 861, 501))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_30 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_30.setObjectName("label_30")
        self.verticalLayout.addWidget(self.label_30)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_31 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_3.addWidget(self.label_31)
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_3.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_3.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_3.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_3.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_3.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_3.addWidget(self.label_21)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_32 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_2.addWidget(self.label_32)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_34 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_8.addWidget(self.label_34)
        self.label_35 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_8.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_8.addWidget(self.label_36)
        self.label_37 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_8.addWidget(self.label_37)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_5)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 861, 501))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_43 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_9.addWidget(self.label_43)
        self.label_44 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_9.addWidget(self.label_44)
        self.label_45 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_9.addWidget(self.label_45)
        self.label_46 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_9.addWidget(self.label_46)
        self.label_47 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_9.addWidget(self.label_47)
        self.label_48 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_9.addWidget(self.label_48)
        self.label_49 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_9.addWidget(self.label_49)
        self.label_50 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_9.addWidget(self.label_50)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_51 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_51.setObjectName("label_51")
        self.verticalLayout_10.addWidget(self.label_51)
        self.label_52 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_52.setObjectName("label_52")
        self.verticalLayout_10.addWidget(self.label_52)
        self.label_53 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_53.setObjectName("label_53")
        self.verticalLayout_10.addWidget(self.label_53)
        self.label_54 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_10.addWidget(self.label_54)
        self.label_55 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_55.setObjectName("label_55")
        self.verticalLayout_10.addWidget(self.label_55)
        self.label_56 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_56.setObjectName("label_56")
        self.verticalLayout_10.addWidget(self.label_56)
        self.label_57 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_57.setObjectName("label_57")
        self.verticalLayout_10.addWidget(self.label_57)
        self.label_58 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_58.setObjectName("label_58")
        self.verticalLayout_10.addWidget(self.label_58)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_59 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_59.setObjectName("label_59")
        self.verticalLayout_11.addWidget(self.label_59)
        self.label_60 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_60.setObjectName("label_60")
        self.verticalLayout_11.addWidget(self.label_60)
        self.label_61 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_61.setObjectName("label_61")
        self.verticalLayout_11.addWidget(self.label_61)
        self.label_62 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_62.setObjectName("label_62")
        self.verticalLayout_11.addWidget(self.label_62)
        self.label_63 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_63.setObjectName("label_63")
        self.verticalLayout_11.addWidget(self.label_63)
        self.label_64 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_64.setObjectName("label_64")
        self.verticalLayout_11.addWidget(self.label_64)
        self.label_65 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_65.setObjectName("label_65")
        self.verticalLayout_11.addWidget(self.label_65)
        self.label_66 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_66.setObjectName("label_66")
        self.verticalLayout_11.addWidget(self.label_66)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_67 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_67.setObjectName("label_67")
        self.verticalLayout_12.addWidget(self.label_67)
        self.label_68 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_68.setObjectName("label_68")
        self.verticalLayout_12.addWidget(self.label_68)
        self.label_69 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_69.setObjectName("label_69")
        self.verticalLayout_12.addWidget(self.label_69)
        self.label_70 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_70.setObjectName("label_70")
        self.verticalLayout_12.addWidget(self.label_70)
        self.horizontalLayout_5.addLayout(self.verticalLayout_12)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(440, 10, 431, 241))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_41 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_6.addWidget(self.label_41)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_38 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_4.addWidget(self.label_38)
        self.label_39 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_4.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_4.addWidget(self.label_40)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.label_33 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_6.addWidget(self.label_33)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_6.addWidget(self.pushButton_2)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 401, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_93 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_93.sizePolicy().hasHeightForWidth())
        self.label_93.setSizePolicy(sizePolicy)
        self.label_93.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_93.setAlignment(QtCore.Qt.AlignCenter)
        self.label_93.setObjectName("label_93")
        self.verticalLayout_19.addWidget(self.label_93)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_28 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_28.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_28.setAutoFillBackground(False)
        self.label_28.setScaledContents(False)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_7.addWidget(self.label_28)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_4.addWidget(self.label_23)
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_4.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_4.addWidget(self.label_26)
        self.label_29 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_4.addWidget(self.label_29)
        self.label_27 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_4.addWidget(self.label_27)
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_4.addWidget(self.label_24)
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_4.addWidget(self.label_22)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_5.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_5.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_5.addWidget(self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_5.addWidget(self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_5.addWidget(self.lineEdit_8)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_5.addWidget(self.lineEdit_9)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_5.addWidget(self.lineEdit_10)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_85 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_85.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_85.setAutoFillBackground(False)
        self.label_85.setScaledContents(False)
        self.label_85.setAlignment(QtCore.Qt.AlignCenter)
        self.label_85.setObjectName("label_85")
        self.verticalLayout_16.addWidget(self.label_85)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_86 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_86.setObjectName("label_86")
        self.verticalLayout_17.addWidget(self.label_86)
        self.label_87 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_87.setObjectName("label_87")
        self.verticalLayout_17.addWidget(self.label_87)
        self.label_88 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_88.setObjectName("label_88")
        self.verticalLayout_17.addWidget(self.label_88)
        self.label_89 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_89.setObjectName("label_89")
        self.verticalLayout_17.addWidget(self.label_89)
        self.label_90 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_90.setObjectName("label_90")
        self.verticalLayout_17.addWidget(self.label_90)
        self.label_91 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_91.setObjectName("label_91")
        self.verticalLayout_17.addWidget(self.label_91)
        self.label_92 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_92.setObjectName("label_92")
        self.verticalLayout_17.addWidget(self.label_92)
        self.horizontalLayout_7.addLayout(self.verticalLayout_17)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.verticalLayout_18.addWidget(self.lineEdit_11)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.verticalLayout_18.addWidget(self.lineEdit_12)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.verticalLayout_18.addWidget(self.lineEdit_13)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.verticalLayout_18.addWidget(self.lineEdit_14)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.verticalLayout_18.addWidget(self.lineEdit_15)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.verticalLayout_18.addWidget(self.lineEdit_16)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.verticalLayout_18.addWidget(self.lineEdit_17)
        self.horizontalLayout_7.addLayout(self.verticalLayout_18)
        self.verticalLayout_16.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout_16)
        self.verticalLayout_19.addLayout(self.horizontalLayout_8)
        self.refreshButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.refreshButton.setObjectName("refreshButton")
        self.verticalLayout_19.addWidget(self.refreshButton)
        self.setAngleButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.setAngleButton.setObjectName("setAngleButton")
        self.verticalLayout_19.addWidget(self.setAngleButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(490, 280, 351, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_94 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_94.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_94.setAlignment(QtCore.Qt.AlignCenter)
        self.label_94.setObjectName("label_94")
        self.verticalLayout_20.addWidget(self.label_94)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_95 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_95.setObjectName("label_95")
        self.horizontalLayout_9.addWidget(self.label_95)
        self.leftGripperSlider = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.leftGripperSlider.setMaximum(10)
        self.leftGripperSlider.setPageStep(2)
        self.leftGripperSlider.setOrientation(QtCore.Qt.Horizontal)
        self.leftGripperSlider.setObjectName("leftGripperSlider")
        self.horizontalLayout_9.addWidget(self.leftGripperSlider)
        self.verticalLayout_21.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_96 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_96.setObjectName("label_96")
        self.horizontalLayout_10.addWidget(self.label_96)
        self.rightGripperSlider = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.rightGripperSlider.setMaximum(10)
        self.rightGripperSlider.setPageStep(2)
        self.rightGripperSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rightGripperSlider.setObjectName("rightGripperSlider")
        self.horizontalLayout_10.addWidget(self.rightGripperSlider)
        self.verticalLayout_21.addLayout(self.horizontalLayout_10)
        self.verticalLayout_20.addLayout(self.verticalLayout_21)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab_6)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 871, 481))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_71 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_71.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_71.setObjectName("label_71")
        self.verticalLayout_13.addWidget(self.label_71)
        self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_13.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_13.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_13.addWidget(self.radioButton_3)
        self.setRPButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.setRPButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.setRPButton.setObjectName("setRPButton")
        self.verticalLayout_13.addWidget(self.setRPButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_72 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_72.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_72.setFont(font)
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName("label_72")
        self.verticalLayout_14.addWidget(self.label_72)
        self.connectRPButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectRPButton.sizePolicy().hasHeightForWidth())
        self.connectRPButton.setSizePolicy(sizePolicy)
        self.connectRPButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.connectRPButton.setAutoFillBackground(False)
        self.connectRPButton.setCheckable(False)
        self.connectRPButton.setObjectName("connectRPButton")
        self.verticalLayout_14.addWidget(self.connectRPButton, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_6.addLayout(self.verticalLayout_14)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.playButton = QtWidgets.QPushButton(self.tab_3)
        self.playButton.setGeometry(QtCore.QRect(420, 60, 101, 91))
        self.playButton.setObjectName("playButton")
        self.recordButton = QtWidgets.QPushButton(self.tab_3)
        self.recordButton.setGeometry(QtCore.QRect(90, 60, 101, 91))
        self.recordButton.setObjectName("recordButton")
        self.stopButton = QtWidgets.QPushButton(self.tab_3)
        self.stopButton.setGeometry(QtCore.QRect(250, 270, 101, 91))
        self.stopButton.setObjectName("stopButton")
        self.label_42 = QtWidgets.QLabel(self.tab_3)
        self.label_42.setGeometry(QtCore.QRect(200, 170, 221, 71))
        self.label_42.setObjectName("label_42")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget.addTab(self.tab_7, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_30.setText(_translate("Dialog", "Joint Name"))
        self.label_2.setText(_translate("Dialog", "Joint0"))
        self.label.setText(_translate("Dialog", "Joint1"))
        self.label_4.setText(_translate("Dialog", "Joint2"))
        self.label_3.setText(_translate("Dialog", "Joint3"))
        self.label_5.setText(_translate("Dialog", "Joint4"))
        self.label_7.setText(_translate("Dialog", "Joint5"))
        self.label_6.setText(_translate("Dialog", "Joint6"))
        self.label_31.setText(_translate("Dialog", "Angle(radian)"))
        self.label_15.setText(_translate("Dialog", "j0a"))
        self.label_16.setText(_translate("Dialog", "j1a"))
        self.label_17.setText(_translate("Dialog", "j2a"))
        self.label_18.setText(_translate("Dialog", "j3a"))
        self.label_19.setText(_translate("Dialog", "j4a"))
        self.label_20.setText(_translate("Dialog", "j5a"))
        self.label_21.setText(_translate("Dialog", "j6a"))
        self.label_32.setText(_translate("Dialog", "Velocity(rad/s)"))
        self.label_8.setText(_translate("Dialog", "j0v"))
        self.label_9.setText(_translate("Dialog", "j1v"))
        self.label_10.setText(_translate("Dialog", "j2v"))
        self.label_11.setText(_translate("Dialog", "j3v"))
        self.label_12.setText(_translate("Dialog", "j4v"))
        self.label_13.setText(_translate("Dialog", "j5v"))
        self.label_14.setText(_translate("Dialog", "j6v"))
        self.label_34.setText(_translate("Dialog", "Cartesian Pose"))
        self.label_35.setText(_translate("Dialog", "Xpose"))
        self.label_36.setText(_translate("Dialog", "Ypose"))
        self.label_37.setText(_translate("Dialog", "Zpose"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Dialog", "Left Arm"))
        self.label_43.setText(_translate("Dialog", "Joint Name"))
        self.label_44.setText(_translate("Dialog", "Joint0"))
        self.label_45.setText(_translate("Dialog", "Joint1"))
        self.label_46.setText(_translate("Dialog", "Joint2"))
        self.label_47.setText(_translate("Dialog", "Joint3"))
        self.label_48.setText(_translate("Dialog", "Joint4"))
        self.label_49.setText(_translate("Dialog", "Joint5"))
        self.label_50.setText(_translate("Dialog", "Joint6"))
        self.label_51.setText(_translate("Dialog", "Angle(radian)"))
        self.label_52.setText(_translate("Dialog", "j0a"))
        self.label_53.setText(_translate("Dialog", "j1a"))
        self.label_54.setText(_translate("Dialog", "j2a"))
        self.label_55.setText(_translate("Dialog", "j3a"))
        self.label_56.setText(_translate("Dialog", "j4a"))
        self.label_57.setText(_translate("Dialog", "j5a"))
        self.label_58.setText(_translate("Dialog", "j6a"))
        self.label_59.setText(_translate("Dialog", "Velocity(rad/s)"))
        self.label_60.setText(_translate("Dialog", "j0v"))
        self.label_61.setText(_translate("Dialog", "j1v"))
        self.label_62.setText(_translate("Dialog", "j2v"))
        self.label_63.setText(_translate("Dialog", "j3v"))
        self.label_64.setText(_translate("Dialog", "j4v"))
        self.label_65.setText(_translate("Dialog", "j5v"))
        self.label_66.setText(_translate("Dialog", "j6v"))
        self.label_67.setText(_translate("Dialog", "Cartesian Pose"))
        self.label_68.setText(_translate("Dialog", "Xpose"))
        self.label_69.setText(_translate("Dialog", "Ypose"))
        self.label_70.setText(_translate("Dialog", "Zpose"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Dialog", "Right Arm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Info"))
        self.label_41.setText(_translate("Dialog", "Current Cartesian Position"))
        self.label_38.setText(_translate("Dialog", "Xpose"))
        self.label_39.setText(_translate("Dialog", "Ypose"))
        self.label_40.setText(_translate("Dialog", "Zpose"))
        self.label_33.setText(_translate("Dialog", "Desire Cartesian Position"))
        self.pushButton.setText(_translate("Dialog", "Go(Currently not availble)"))
        self.pushButton_2.setText(_translate("Dialog", "Home Kinova Arm"))
        self.label_93.setText(_translate("Dialog", "Angle Control"))
        self.label_28.setText(_translate("Dialog", "Left Arm"))
        self.label_23.setText(_translate("Dialog", "Joint0"))
        self.label_25.setText(_translate("Dialog", "Joint1"))
        self.label_26.setText(_translate("Dialog", "Joint2"))
        self.label_29.setText(_translate("Dialog", "Joint3"))
        self.label_27.setText(_translate("Dialog", "Joint4"))
        self.label_24.setText(_translate("Dialog", "Joint5"))
        self.label_22.setText(_translate("Dialog", "Joint6"))
        self.label_85.setText(_translate("Dialog", "Right Arm"))
        self.label_86.setText(_translate("Dialog", "Joint0"))
        self.label_87.setText(_translate("Dialog", "Joint1"))
        self.label_88.setText(_translate("Dialog", "Joint2"))
        self.label_89.setText(_translate("Dialog", "Joint3"))
        self.label_90.setText(_translate("Dialog", "Joint4"))
        self.label_91.setText(_translate("Dialog", "Joint5"))
        self.label_92.setText(_translate("Dialog", "Joint6"))
        self.refreshButton.setText(_translate("Dialog", "Get Current Angle"))
        self.setAngleButton.setText(_translate("Dialog", "Set Angle"))
        self.label_94.setText(_translate("Dialog", "Gripper Control"))
        self.label_95.setText(_translate("Dialog", " Left  "))
        self.label_96.setText(_translate("Dialog", " Right "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Control"))
        self.label_71.setText(_translate("Dialog", "Control Mode"))
        self.radioButton.setText(_translate("Dialog", "Only left arm"))
        self.radioButton_2.setText(_translate("Dialog", "Only right arm"))
        self.radioButton_3.setText(_translate("Dialog", "Both arms"))
        self.setRPButton.setText(_translate("Dialog", "Confirm"))
        self.label_72.setText(_translate("Dialog", "TextLabel"))
        self.connectRPButton.setText(_translate("Dialog", "Enable/Disable Connection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "Robopuppet Settings"))
        self.playButton.setText(_translate("Dialog", "Play"))
        self.recordButton.setText(_translate("Dialog", "Record"))
        self.stopButton.setText(_translate("Dialog", "Stop"))
        self.label_42.setText(_translate("Dialog", "I will make this nicer --- Jack"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Learn"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Dialog", "Plots"))

